source "https://rubygems.org"

gem 'sass',               "~> 3.4.0.rc.3"
gem 'compass',            "~>1.0.0.rc.1"
gem 'breakpoint',         "~> 2.4"
gem 'sass-globbing',      "<= 1.1.0"
gem 'singularitygs',      "< 2.0.0"
