<?php
/**
 * @file
 * atom_terms_of_service functionality
 */

/**
 * Creates the Terms of Service page.
 *
 * This will create a page node with a path of "/terms-of-use" if:
 *
 * - something doesn't already exist at /terms-of-use
 * - and the page content type exists
 *
 * @return mixed
 *   Return's the node object if successful or NULL if not.
 */
function atom_terms_of_use_create_page() {
  if (drupal_lookup_path('source', 'terms-of-use') === FALSE) {
    $info = entity_get_info('node');
    if (isset($info['bundles']['page'])) {

      // create the node
      $page = new stdClass();
      $page->type = 'page';
      $page->title = 'Terms of Use';
      $language = LANGUAGE_NONE;
      $page->language = $language;
      $page->path = array(
        'alias' => 'terms-of-use',
        'pathauto' => FALSE,
      );
      node_object_prepare($page);
      $page->uid = 1;
      $page->body[$language][0]['value'] = "Terms of Use";
      $page->body[$language][0]['format'] = filter_default_format();
      $page = node_submit($page);
      node_save($page);

      // check if the menu exists
      $menus = menu_get_menus();
      if (!isset($menus['menu-footer-menu'])) {
        watchdog('atom_terms_of_use', 'Terms of Use page could not be added to the footer menu because the menu does not exist', array(), WATCHDOG_ERROR, l(t('Menus'), '/admin/structure/menu'));
        return $page;
      }

      $menu_item = array(
        'link_path' => 'node/' . $page->nid,
        'link_title' => $page->title,
        'menu_name' => 'menu-footer-menu',
        'weight' => 0,
        'language' => $page->language,
        'plid' => 0,
        'module' => 'menu',
      );
      $exists = db_query(
        "SELECT mlid from {menu_links} WHERE link_title=:link_title AND link_path=:link_path AND menu_name=:menu_name",
        array(
          ':link_title' => $menu_item['link_title'],
          ':link_path' => $menu_item['link_path'],
          ':menu_name' => $menu_item['menu_name'],
        )
      )->fetchField();

      if (!$exists) {
        if ($mlid = menu_link_save($menu_item)) {
          menu_cache_clear_all();
          watchdog('atom_terms_of_use', 'Terms of Use menu item added', array(), WATCHDOG_NOTICE, l(t('Footer menu'), '/admin/structure/menu/manage/menu-footer-menu/list'));
        }
        else {
          watchdog('atom_terms_of_use', 'Terms of Use menu item already was not saved', array(), WATCHDOG_ERROR, l(t('Footer menu'), '/admin/structure/menu/manage/menu-footer-menu/list'));
        }
      }
      else {
        watchdog('atom_terms_of_use', 'Terms of Use menu item already exists', array(), WATCHDOG_NOTICE, l(t('Footer menu'), '/admin/structure/menu/manage/menu-footer-menu/list'));
      }

      watchdog('atom_terms_of_use', 'Terms of Use page created', array(), WATCHDOG_NOTICE, l(t('View'), 'node/' . $page->nid));
      return $page;
    }

    watchdog('atom_terms_of_use', 'Terms of Use page was not created because the page content type does not exist', array(), WATCHDOG_ERROR);
    return NULL;
  }

  watchdog('atom_terms_of_use', 'Terms of Use page was not created because something already exists at /terms-of-use', array(), WATCHDOG_NOTICE);
  return NULL;
}

/**
 * Disable the footer menu link.
 *
 * Called from atom_terms_of_use_disable().
 */
function atom_terms_of_use_disable_menu_link() {
  if ($path = drupal_get_normal_path('terms-of-use')) {
    db_update('menu_links')
      ->fields(array('hidden' => 1))
      ->condition('link_path', $path)
      ->condition('menu_name', 'menu-footer-menu')
      ->execute();
  }
}
