<?php
/**
 * @file
 * openaid_home functionality
 */

/**
 * Create a home page
 */
function openaid_home_create_page() {
  $site_frontpage = variable_get('site_frontpage');
  $openaid_home = drupal_lookup_path('source', 'openaid-home');
  if (!$openaid_home) {
    $info = entity_get_info('node');
    if (isset($info['bundles']['page'])) {
      // create the node
      $page = new stdClass();
      $page->type = 'page';
      $page->title = 'Home';
      $language = LANGUAGE_NONE;
      $page->language = $language;
      $page->path = array(
        'alias' => 'openaid-home',
        'pathauto' => FALSE,
      );
      node_object_prepare($page);
      $page->uid = 1;

      // create the home page content
      $content = "";

      $page->body[$language][0]['value'] = $content;
      $page->body[$language][0]['format'] = filter_default_format();
      $page = node_submit($page);
      node_save($page);

      // Set the frontpage variable to the page nid
      if ($site_frontpage) {
        variable_set('original_site_frontpage', variable_get('site_frontpage'));
      }
      variable_set('site_frontpage', 'node/' . $page->nid);

      // check if the menu exists
      $menus = menu_get_menus();
      if (!isset($menus['main-menu'])) {
        watchdog('openaid_home', 'Home page could not be added to the main menu because the menu does not exist', array(), WATCHDOG_ERROR, l(t('Menus'), '/admin/structure/menu'));
        return $page;
      }

      $menu_item = array(
        'link_path' => 'node/' . $page->nid,
        'link_title' => $page->title,
        'menu_name' => 'main-menu',
        'weight' => -50,
        'language' => $page->language,
        'plid' => 0,
        'module' => 'menu',
      );
      $exists = db_query(
        "SELECT mlid from {menu_links} WHERE link_title=:link_title AND link_path=:link_path AND menu_name=:menu_name",
        array(
          ':link_title' => $menu_item['link_title'],
          ':link_path' => $menu_item['link_path'],
          ':menu_name' => $menu_item['menu_name'],
        )
      )->fetchField();

      if (!$exists) {
        if ($mlid = menu_link_save($menu_item)) {
          menu_cache_clear_all();
          watchdog('openaid_home', 'Home menu item added', array(), WATCHDOG_NOTICE, l(t('Main menu'), '/admin/structure/menu/manage/main-menu'));
        }
        else {
          watchdog('openaid_home', 'Home menu item already was not saved', array(), WATCHDOG_ERROR, l(t('Main menu'), '/admin/structure/menu/manage/main-menu'));
        }
      }
      else {
        watchdog('openaid_home', 'Home menu item already exists', array(), WATCHDOG_NOTICE, l(t('Main menu'), '/admin/structure/menu/manage/main-menu'));
      }

      watchdog('openaid_home', 'Home page created', array(), WATCHDOG_NOTICE, l(t('View'), 'node/' . $page->nid));
      return $page;
    }

    watchdog('openaid_home', 'Home page was not created because the page content type does not exist', array(), WATCHDOG_ERROR);
    return NULL;
  }

  watchdog('openaid_home', 'Home page was not created because content already exists at /openaid-home', array(), WATCHDOG_NOTICE);
  variable_set('site_frontpage', $source);
  watchdog('openaid_home', 'Home page was set to %source', array('%source' => $source), WATCHDOG_NOTICE);
  return NULL;
}
